// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://citmptpriseuzppmewpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpdG1wdHByaXNldXpwcG1ld3BmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDE2MTEsImV4cCI6MjA3MTg3NzYxMX0.-rHn0yNqhB0YgfFrB_nX83W2DvKCEY5Z5jzmdPxfIW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});